CREATE TABLE users (
                       id SERIAL PRIMARY KEY,
                       gender VARCHAR(10) NOT NULL,
                       title VARCHAR(10) NOT NULL,
                       first_name VARCHAR(50) NOT NULL,
                       last_name VARCHAR(50) NOT NULL,
                       street_number INTEGER NOT NULL,
                       street_name VARCHAR(100) NOT NULL,
                       city VARCHAR(100) NOT NULL,
                       state VARCHAR(100) NOT NULL,
                       country VARCHAR(100) NOT NULL,
                       postcode VARCHAR(10) NOT NULL,
                       latitude DECIMAL(10, 7) NOT NULL,
                       longitude DECIMAL(10, 7) NOT NULL,
                       timezone_offset VARCHAR(10) NOT NULL,
                       timezone_description VARCHAR(50) NOT NULL,
                       email VARCHAR(100) NOT NULL,
                       uuid VARCHAR(36) NOT NULL,
                       username VARCHAR(50) NOT NULL,
                       password VARCHAR(100) NOT NULL,
                       salt VARCHAR(20) NOT NULL,
                       md5 VARCHAR(32) NOT NULL,
                       sha1 VARCHAR(40) NOT NULL,
                       sha256 VARCHAR(64) NOT NULL,
                       dob DATE NOT NULL,
                       age INTEGER NOT NULL,
                       reg_date DATE NOT NULL,
                       reg_age INTEGER NOT NULL,
                       phone VARCHAR(20) NOT NULL,
                       cell VARCHAR(20) NOT NULL,
                       id_name VARCHAR(20) NOT NULL,
                       id_value VARCHAR(20) NOT NULL,
                       picture_large VARCHAR(200) NOT NULL,
                       picture_medium VARCHAR(200) NOT NULL,
                       picture_thumbnail VARCHAR(200) NOT NULL,
                       nat VARCHAR(2) NOT NULL
);